### ISSUE TITLE
why detect json file to plainText

### ISSUE THREAD

**Issue by MoonJustry** [zRedShift/mimemagic#2]
json data like 
```
{
    "key":"value"
}
```
but Match result is text/plain

**Comment by zRedShift** [comment]
There is no magic file signature for JSON files in the XDG shared-mime-info database, it only matches by glob (*.json). Since JSON isn't a regular language, it can't be trivially ascertained using byte-by-byte comparisons and searches. [Here's how file/libmagic does it](https://github.com/file/file/blob/master/src/is_json.c). If you'd like to work on porting that code to Go, mimemagic could be trivially extended to implement the same functionality.
